repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip3 freeze > requirements.lock.txt; git add requirements.lock.txt'
        language: system
        pass_filenames: false
        stages: [commit]
