version: '3.7'

services:
  calibration:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app
      depends_on:
        - calibration-db
      env_file:
        - .env
  calibration-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - calibration-db_data:/var/lib/postgresql/data/
  
volumes:
  calibration-db_data:
