# Generated by Django 3.2.4 on 2021-06-25 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(help_text='Digite um nome para identificar sua análise.', max_length=255, verbose_name='Nome da Análise')),
                ('substance_name', models.CharField(help_text='Digite o nome da substância que você está analisando.', max_length=255, verbose_name='Nome da Substância')),
                ('absorbance', models.CharField(help_text='Valores das absorbâncias lidas separados por vírgula.', max_length=255, verbose_name='Absorbâncias')),
                ('concentration', models.CharField(help_text='Valores das concentrações para cada absorbância fornecida separados por vírgulas.', max_length=255, verbose_name='Concentrações')),
                ('concentration_units', models.CharField(choices=[('mg/l', 'mg/l'), ('g/l', 'g/l'), ('mg/ml', 'mg/ml'), ('mol/l', 'mol/l')], default='mg/l', help_text='Valores das unidades das concentrações.', max_length=255, verbose_name='Unidades das Concentrações')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('analyst', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
            },
        ),
    ]
