# Generated by Django 3.2.4 on 2021-07-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0003_alter_analysis_concentration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="absorbance",
            field=models.CharField(
                help_text="Valores das absorbâncias lidas separadas por vírgula.",
                max_length=255,
                verbose_name="Absorbâncias",
            ),
        ),
    ]
